name: ogu_schedule
description: Ogu schedule for students
version: 1.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  intl_translation: ^0.17.9
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/normal/roboto_regular.ttf
        - asset: assets/fonts/roboto/normal/roboto_medium.ttf
          weight: 600
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/roboto/slab/roboto_slab_regular.ttf
        - asset: assets/fonts/roboto/slab/roboto_slab_bold.ttf
          weight: 700